version: "3.9"
services:
  camcode-api:
    build:
      context: ./server
      dockerfile: ./Dockerfile-dev
    ports:
      - "8081:8081"
    volumes:
      - './server:/app'

  camcode-client:
    build:
      context: ./camcode-client
      dockerfile: ./Dockerfile-dev
    ports:
      - '3000:3000'
    volumes:
      - './camcode-client:/app'

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile-dev
    ports:
      - "443:443"

#docker-compose -f docker-compose-dev.yml up --build
