FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./cer/keys.key /etc/ssl/camcode/localhost.key
COPY ./cer/bundle.crt /etc/ssl/camcode/localhost.crt
