FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./cer/localhost.crt /etc/ssl/camcode/localhost.crt
COPY ./cer/localhost.key /etc/ssl/camcode/localhost.key
