
FROM node:alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_APP_BASE_URL='https://apps.varcode.com:3443/api'
ENV VITE_APP_BASE_URL='https://apps.varcode.com:3443/api'
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
COPY ./cer/keys.key /etc/ssl/camcode/localhost.key
COPY ./cer/bundle.crt /etc/ssl/camcode/localhost.crt
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

#docker build -f ./Dockerfile-prod -t camcode-client-prod .
